---
title: "AD_Apr12"
author: "Haowen Zhou"
date: "4/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Data

```{r load}

setwd("~/Desktop/At_Broad/AD")
#Convert Data
#Convert("data/2021-04-22-starmap-mAD-64-genes-raw.h5ad", dest = "h5seurat", overwrite = TRUE)
#Convert("data/2021-04-22-starmap-mAD-raw.h5ad", dest = "h5seurat", overwrite = TRUE)

source("RScript/AD_FunctionDefinition.R")
source("RScript/AD_DE_Function.R")
source("RScript/AD_SpatialFunction.R")
source("RScript/AD_Pseudo-timeFunction.R")
#Load Scaled Data
ad_ini()
starmap <- LoadH5Seurat("data/2020-12-27-starmap-mAD-scaled.h5seurat")
X2021_06_04_obs <- read_csv("data/2021-06-04-obs.csv")
starmap@meta.data$cell_type <- X2021_06_04_obs$cell_type


starmap_raw <- LoadH5Seurat("data/2021-04-22-starmap-mAD-raw.h5seurat")

starmap_64 <- LoadH5Seurat("data/2021-04-22-starmap-mAD-64-genes-raw.h5seurat")

colnames(starmap_64@meta.data)[19] <- "cell_type"
colnames(starmap_64@meta.data)[21] <- "cell_type_label"
```

```{r Prepare}
#AD palette list
top_level_palette_list <- as.character(unlist(starmap_raw@misc[["top_hex_dict"]]))[!colnames(starmap_raw@misc[["top_hex_dict"]]) %in% c("DG","LHb")]
names(top_level_palette_list) <- colnames(starmap_raw@misc[["top_hex_dict"]])[!colnames(starmap_raw@misc[["top_hex_dict"]]) %in% c("DG","LHb")]
#AD_64 palette list
top_level_palette_list_64 <- as.character(unlist(starmap_64@misc[["top_hex_dict_64"]]))
names(top_level_palette_list_64) <- names(unlist(starmap_64@misc[["top_hex_dict_64"]]))
top_level_palette_list_64 <- c(top_level_palette_list_64[!names(top_level_palette_list_64) %in% c("DG","LHb")])
top_level_palette_list_64[["Mix"]] <- "#8c8c8c"

cell_type_list <- list("Ex" = c("L2/3" ,"L4/5_RSC_A","L4/5_RSC_B","L6"),
                       "Micro" = c("Micro", "Micro_Gpr34", "Micro_Cst7/Ctsb"),
                       "Oligo" = c("Oligo", "Oligo_Klk6", "Oligo_Cldn11","OPC"),
                       "Astro" = c("Astro","Astro_Cst3","Astro_Gfap/Vim"),
                       #"OPC" = c("OPC","OPC_Gpr17"),
                       "Inhi" = c("Cnr1","Lamp5","Pvalb","Pvalb_Nog","Sst","Vip"),
                       "CADG" = c("CA1","CA2","CA3","DG"))
cell_type_palette_list <- list("Ex" = c("L2/3"="#f4777c", "L4/5_RSC_A"="#f8bf76", 
                                        "L4/5_RSC_B"="#fdfe02","L6"="#b0ff00"),
                    "Micro" = c("Micro"="#2fe04d", "Micro_Gpr34"="#2c73e6", "Micro_Cst7/Ctsb"="#fa733e"),
                    "Oligo" = c("Oligo"="#2fe04d", "Oligo_Klk6"="#2c73e6", 
                                "Oligo_Cldn11"="#fa733e", "OPC"="#8600d4"),
                    "Astro" = c("Astro"="#2fe04d","Astro_Cst3"="#2c73e6","Astro_Gfap/Vim"="#fa733e"),
                    #"OPC" = c("#0dd193","#7a9deb"),
                    "Inhi" = c("Cnr1"="#3774f8","Lamp5"="#2fccc2","Pvalb"="#43b500",
                               "Pvalb_Nog"="#bcaa03","Sst"="#f19cd3","Vip"="#bd3a3a"),
                    "CADG" = c("CA1"="#90fffe","CA2"="#3b92ff","CA3"="#9600ff","DG"="#95000a"))
```

## Calc Plaque Border-Dist

```{r calc border-dist}
starmap <- ad_calc_plaque_dist(starmap,starmap@misc[["AD_mouse9494_morph"]], 400, "AD_mouse9494", top_level_palette_list, "all")
starmap <- ad_calc_plaque_dist(starmap,starmap@misc[["AD_mouse9494_morph"]], 400, "AD_mouse9494", top_level_palette_list, "Cortex")
starmap <- ad_calc_plaque_dist(starmap,starmap@misc[["AD_mouse9494_morph"]], 400, "AD_mouse9494", top_level_palette_list, "White Matter")
starmap <- ad_calc_plaque_dist(starmap,starmap@misc[["AD_mouse9494_morph"]], 400, "AD_mouse9494", top_level_palette_list, "Hippocampus")

starmap <- ad_calc_plaque_dist(starmap,starmap@misc[["AD_mouse9723_morph"]], 400, "AD_mouse9723", top_level_palette_list, "all")
starmap <- ad_calc_plaque_dist(starmap,starmap@misc[["AD_mouse9723_morph"]], 400, "AD_mouse9723", top_level_palette_list, "Cortex")
starmap <- ad_calc_plaque_dist(starmap,starmap@misc[["AD_mouse9723_morph"]], 400, "AD_mouse9723", top_level_palette_list, "White Matter")
starmap <- ad_calc_plaque_dist(starmap,starmap@misc[["AD_mouse9723_morph"]], 400, "AD_mouse9723", top_level_palette_list, "Hippocampus")

starmap_64 <- ad_calc_plaque_dist(starmap_64,starmap_64@misc[["AD_mouse9721_morph"]], 400, "AD_mouse9721", top_level_palette_list_64, "all")
starmap_64 <- ad_calc_plaque_dist(starmap_64,starmap_64@misc[["AD_mouse9919_morph"]], 400, "AD_mouse9919", top_level_palette_list_64, "all")

```

##Plot cell type distribution

```{r figure export}
#Running in console
scale_density_max <- list()
scale_density_max[["Cortex"]]       <- c("Micro"=3000,"Astro"=500,"Oligo"=2500, "Ex"=2000,"Inhi"=250)
scale_density_max[["White Matter"]] <- c("Micro"=300, "Astro"=200,"Oligo"=200, "Ex"=200,"Inhi"=250)
scale_density_max[["Hippocampus"]]  <- c("Micro"=2000,"Astro"=400,"Oligo"=500, "Ex"=200,"Inhi"=250)
ad_distr_fig_export_regional(starmap, "AD_mouse9494",cell_type_list,cell_type_palette_list,scale_density_max = scale_density_max)

scale_density_max <- list()
scale_density_max[["Cortex"]]       <- c("Micro"=3000,"Astro"=400,"Oligo"=700, "Ex"=2000,"Inhi"=300)
scale_density_max[["White Matter"]] <- c("Micro"=100, "Astro"=100,"Oligo"=200, "Ex"=200,"Inhi"=300)
scale_density_max[["Hippocampus"]]  <- c("Micro"=100,"Astro"=100,"Oligo"=100, "Ex"=200,"Inhi"=300)
ad_distr_fig_export_regional(starmap, "AD_mouse9723", cell_type_list,cell_type_palette_list, scale_density_max = scale_density_max,
                    scale_max = c("Micro"=1,"Astro"=0.75,"Oligo"=1, "Ex"=0.6,"Inhi"=0.15,"CADG" = 0.6))

ad_distr_fig_export_all(starmap_64, "AD_mouse9919", cell_type_list, cell_type_palette_list,
                    scale_max = c("Micro"=0.75,"Astro"=0.2,"Oligo"=0.25, "Ex"=0.3,"Inhi"=0.1))
ad_distr_fig_export_all(starmap_64, "AD_mouse9721", cell_type_list, cell_type_palette_list, 
                    scale_max = c("Micro"=0.75,"Astro"=0.2,"Oligo"=0.25, "Ex"=0.3,"Inhi"=0.1))

pdf(file = "F2S_Overall_density.pdf",width = 12,height = 9)
starmap@misc$AD_mouse9494_plaque_all$AD_mouse9494_t_l_d_plotlist[[2]] %>% print()
starmap@misc$AD_mouse9723_plaque_all$AD_mouse9723_t_l_d_plotlist[[2]] %>% print()
starmap_64@misc$AD_mouse9919_plaque_all$AD_mouse9919_t_l_d_plotlist[[2]] %>% print()
starmap_64@misc$AD_mouse9721_plaque_all$AD_mouse9721_t_l_d_plotlist[[2]] %>% print()
dev.off()




```

## Gene Expression among min_dist

```{r spatial}
#Micro
gene_list <- c("CST7", "GFAP", "CTSB", "APOE", "JPH4", "CALM1", "P2RY12", "TGFBR1", "GPR34", "C1QA", "TREM2",
               "CD83","CD9","C1QA","CTSS")
gene_list <- c("SELPLG","P2RY12", "TGFBR1", "GPR34", "C1QA", "TREM2",
               "CD83","CD9","CLEC7A", "CTSB","CTSL", "CST7", "APOE", "CTSS")
#Astro
gene_list <- c("GFAP", "VIM", "JPH4", "STAT3", "FXYD1", "NRGN", "VSNL1", "CST3", "TSPAN7", "APOE", "AQP4")
gene_list <- c("GFAP", "VIM", "JPH4", "STAT3", "FXYD1", "VSNL1", "CST3", "TSPAN7", "APOE", "AQP4","CLU","ALDOC",
               "CD63","SLC1A3")
#Oligo
gene_list <- c('MBP','VIM','C4B','APLP1','GPM6A','TSPAN7','KLK6','APOD','CLDN11','RCAN2',"CD9","SERPINA3N")
gene_list <- c('PTGDS','PLP1','MOBP','KLK6','TRF','CNTN2','SORT1','APOD','CLDN11','MBP','GFAP','KCNJ2', 
               'RCAN2','C4B','PDGFRA','CACNG4')
gene_list <- c('PLP1','CLDN11','KLK6',"SERPINA3N","C4B","CDKN1A","CD9")
#Inhi
gene_list <- c("CNR1","SST","PVALB","VIP")
#Spatial - 64
#8mo
gene_list <- gene_cl_res_8[["stat_test"]][["gene"]][gene_cl_res_8[["stat_test"]]$p_val < 0.01 &
                                                       gene_cl_res_8[["stat_test"]]$cluster %in% c(5,4,6)] %>%
  as.character() %>% intersect(row.names(starmap_64@assays$RNA@counts))
#13mo
gene_list <- gene_cl_res_13[["stat_test"]][["gene"]][gene_cl_res_13[["stat_test"]]$p_val < 0.01 &
                                                       gene_cl_res_13[["stat_test"]]$cluster %in% c(5,4,6)] %>%
  as.character() %>% intersect(row.names(starmap_64@assays$RNA@counts))

sample_name <- "AD_mouse9919"
cell_type <- "Micro"
#Plot spatial expr
tmp_df <- matrix(0, nrow = length(gene_list), ncol = 5) %>% as.data.frame(row.names = gene_list)
colnames(tmp_df) <- paste("R",1:5,"0",sep = "")
      
tmp_mat <- starmap_64@assays[["RNA"]]@counts[gene_list,
                                              starmap_64@meta.data[["sample"]] == sample_name]
cell_meta <- starmap_64@misc$AD_mouse9919_plaque_all$AD_mouse9919_cell_meta
      
for (i in 1:4) {
        tmp_df[,i] <- rowSums(tmp_mat[,cell_meta$interval == paste(i,"0um",sep = "")])  /
          sum(cell_meta$interval == paste(i,"0um",sep = ""))
        #tmp_df[,i] <- rowSums(tmp_mat[,cell_meta$interval == paste(i,"0um",sep = "") & 
        #                                cell_meta$top_level == cell_type])  /
        #  sum(cell_meta$min_border_dist < i * 33 & cell_meta$min_border_dist >= (i-1) * 33 & 
        #        cell_meta$top_level == cell_type)
}
tmp_df[,5] <- rowSums(tmp_mat[,cell_meta$interval %in% c("other","50um")])  /
          sum(cell_meta$interval %in% c("other","50um"))
require(ComplexHeatmap)
row.names(tmp_df) <- str_to_title(row.names(tmp_df))
Heatmap(t(scale(t(tmp_df[,1:5]))), cluster_columns = F,rect_gp = gpar(col = "black", lwd = 1),
        cluster_rows  = T, show_row_names = T,column_title = paste(sample_name))
#Plot sub type marker
tmp_df <- matrix(0, nrow = length(gene_list), 
                 ncol = length(cell_type_list[[cell_type]])) %>% as.data.frame(row.names = gene_list)
colnames(tmp_df) <- cell_type_list[[cell_type]]
      
tmp_mat <- starmap_raw@assays[["RNA"]]@counts[gene_list,
                                              starmap_raw@meta.data[["sample"]] == sample_name]
cell_meta <- starmap@misc$AD_mouse9494_plaque_all$AD_mouse9494_cell_meta
      
for (i in cell_type_list[[cell_type]]) {
        tmp_df[,i] <- rowSums(tmp_mat[,cell_meta$cell_type == i])  /
          sum(cell_meta$cell_type == i)
      }

Heatmap(t(scale(t(tmp_df))), cluster_columns = F,
        cluster_rows  = F, show_row_names = T,column_title = paste(cell_type))
#cell type and sample
tmp_df <- matrix(0, nrow = length(gene_list), 
                 ncol = 4) %>% as.data.frame(row.names = gene_list)
colnames(tmp_df) <- c("AD_mouse9735","AD_mouse9723","AD_mouse9498","AD_mouse9494")
colnames(tmp_df) <- c("AD_mouse9781","AD_mouse9721","AD_mouse9930","AD_mouse9919")
      
tmp_mat <- starmap_64@assays[["RNA"]]@counts[gene_list,
                                              starmap_64@meta.data[["top_level"]] == cell_type]
cell_meta <- starmap_64@meta.data[starmap_64@meta.data$top_level == cell_type,]
      
for (i in colnames(tmp_df)) {
        tmp_df[,i] <- rowSums(tmp_mat[,cell_meta$sample == i])  /
          sum(cell_meta$sample == i)
      }

Heatmap(t(scale(t(tmp_df))), cluster_columns = F,
        cluster_rows  = F, show_row_names = T,column_title = paste(cell_type))



```

## Archived Codes

```{r Micro}
AD_Micro_pseudotime <- psdtime_res_list[["Micro"]][["cell_meta"]]
tmp <- starmap@meta.data[starmap@meta.data$top_level == "Micro",]
AD_Micro_pseudotime <- data.frame(AD_Micro_pseudotime,
                                  normalized_psdtime = AD_Micro_pseudotime$pseudotime/max(AD_Micro_pseudotime$pseudotime))
AD_Micro_pseudotime <- data.frame(AD_Micro_pseudotime,
                                  psdtime_stage = floor(10 * AD_Micro_pseudotime$normalized_psdtime))
AD_Micro_pseudotime$psdtime_stage[AD_Micro_pseudotime$psdtime_stage == 10] <- 9


gene_list <- row.names(starmap_obj@assays[["RNA"]]@counts)[
    rowSums(starmap_obj@assays[["RNA"]]@counts[,starmap_obj@meta.data[["top_level"]] == "Micro"] > 0)
    > sum(starmap_obj@meta.data[["top_level"]] == "Micro") * 0.1]
tmp_df <- matrix(0, nrow = length(gene_list), ncol = 10) %>% as.data.frame(row.names = gene_list)
colnames(tmp_df) <- paste("stage",0:9,sep = "")
for (i in 0:9) {
    tmp_mat <- starmap_obj@assays[["RNA"]]@counts[gene_list,starmap_obj@meta.data[["top_level"]] == "Micro"]
    tmp_df[,i+1] <- rowSums(tmp_mat[,AD_Micro_pseudotime$psdtime_stage == i]) /
      sum(AD_Micro_pseudotime$psdtime_stage == i)
  }
Heatmap(log2(1+as.matrix(tmp_df[c("CTSS","P2RY12","GPR34","TGFBR1","CST7","CTSB","APOE","CD9","TREM2"),])),cluster_columns = F, show_row_names = F ) 



```

```{r Export psdtime related figures}
ad_plot_psdtime_group <- function(data,x,fill,title,subcortical = F){
  if(subcortical){
    data$region[data$region %in% c("Hippocampus","White Matter")] <- "Sub-cortical"
  }
  data %>% ggplot( aes_string(x = x, y="normalized_psdtime", fill=fill)) +
    geom_boxplot() +
    scale_fill_viridis(discrete = TRUE, alpha=0.6) +
    #geom_jitter(color="black", size=0.4, alpha=0.9) +
    theme_bw() +
    theme(
      
      plot.title = element_text(size=11)
    ) +
    ggtitle(paste("Pseudotime Distribution",title)) +
    xlab("") %>% print()
}

pdf(file = "Aug04_pseudotime_boxplot.pdf",width = 12,height = 9)
ad_plot_psdtime_distr(starmap@misc[["AD_mouse9494_plaque_all"]][["AD_mouse9494_cell_meta"]], 
                      psdtime_res_list[["Micro"]][["cell_meta"]],
                      "AD_mouse9494",
                      "Micro") %>% print()
ad_plot_psdtime_distr(starmap@misc[["AD_mouse9723_plaque_all"]][["AD_mouse9723_cell_meta"]], 
                      psdtime_res_list[["Micro"]][["cell_meta"]],
                      "AD_mouse9723",
                      "Micro") %>% print()

ad_plot_psdtime_distr(starmap@misc[["AD_mouse9494_plaque_all"]][["AD_mouse9494_cell_meta"]], 
                      psdtime_res_list[["Astro"]][["cell_meta"]],
                      "AD_mouse9494",
                      "Astro") %>% print()
ad_plot_psdtime_distr(starmap@misc[["AD_mouse9723_plaque_all"]][["AD_mouse9723_cell_meta"]], 
                      psdtime_res_list[["Astro"]][["cell_meta"]],
                      "AD_mouse9723",
                      "Astro") %>% print()

ad_plot_psdtime_distr(starmap@misc[["AD_mouse9494_plaque_all"]][["AD_mouse9494_cell_meta"]], 
                      psdtime_res_list[["Oligo"]][["cell_meta"]],
                      "AD_mouse9494",
                      c("OPC")) %>% print()
ad_plot_psdtime_distr(starmap@misc[["AD_mouse9494_plaque_all"]][["AD_mouse9494_cell_meta"]], 
                      psdtime_res_list[["Oligo"]][["cell_meta"]],
                      "AD_mouse9494",
                      c("Oligo")) %>% print()
ad_plot_psdtime_distr(starmap@misc[["AD_mouse9723_plaque_all"]][["AD_mouse9723_cell_meta"]], 
                      psdtime_res_list[["Oligo"]][["cell_meta"]],
                      "AD_mouse9723",
                      c("OPC")) %>% print()
ad_plot_psdtime_distr(starmap@misc[["AD_mouse9723_plaque_all"]][["AD_mouse9723_cell_meta"]], 
                      psdtime_res_list[["Oligo"]][["cell_meta"]],
                      "AD_mouse9723",
                      c("Oligo")) %>% print()
dev.off()



AD_Astro_pseudotime %>% ad_plot_psdtime_group(x = "region", fill = "group", title = "Astro", subcortical = T)
AD_Micro_pseudotime %>% ad_plot_psdtime_group(x = "region", fill = "group", title = "Micro", subcortical = T)
AD_OPC_Oligo_pseudotime %>% ad_plot_psdtime_group(x = "region", fill = "group", title = "Oligo/OPC", subcortical = T)




AD_OPC_Oligo_pseudotime %>% ggplot( aes(x=region, y=normalized_psdtime, fill=group)) +
    geom_boxplot() +
    scale_fill_viridis(discrete = TRUE, alpha=0.6) +
    #geom_jitter(color="black", size=0.4, alpha=0.9) +
    theme_bw() +
    theme(
      
      plot.title = element_text(size=11)
    ) +
    ggtitle(paste("Pseudotime Distribution")) +
    xlab("") %>% print()
```

```{r Astro}
#psdtime heatmap
AD_Astro_pseudotime <- read_csv("Export_csv/AD_Astro_pseudotime.csv")
tmp <- starmap@meta.data[starmap@meta.data$top_level == "Astro",]
AD_Astro_pseudotime <- data.frame(AD_Astro_pseudotime,
                                  normalized_psdtime = AD_Astro_pseudotime$pseudotime/max(AD_Astro_pseudotime$pseudotime))
AD_Astro_pseudotime <- data.frame(AD_Astro_pseudotime,
                                  psdtime_stage = floor(10 * AD_Astro_pseudotime$normalized_psdtime))
AD_Astro_pseudotime$psdtime_stage[AD_Astro_pseudotime$psdtime_stage == 10] <- 9

gene_list <- row.names(starmap_obj@assays[["RNA"]]@counts)[
    rowSums(starmap_obj@assays[["RNA"]]@counts[,starmap_obj@meta.data[["top_level"]] == "Astro"] > 0)
    > sum(starmap_obj@meta.data[["top_level"]] == "Astro") * 0.1]
tmp_df <- matrix(0, nrow = length(gene_list), ncol = 10) %>% as.data.frame(row.names = gene_list)
colnames(tmp_df) <- paste("stage",0:9,sep = "")
for (i in 0:9) {
    tmp_mat <- starmap_obj@assays[["RNA"]]@counts[gene_list,starmap_obj@meta.data[["top_level"]] == "Astro"]
    tmp_df[,i+1] <- rowSums(tmp_mat[,AD_Astro_pseudotime$psdtime_stage == i]) /
      sum(AD_Astro_pseudotime$psdtime_stage == i)
  }
Heatmap(log2(1+as.matrix(tmp_df[c("ALDOC","CST3","GFAP","VIM","AQP4","CD63"),])),cluster_columns = F, show_row_names = T ) 
#Scale
Heatmap(t(scale(t(as.matrix(tmp_df[c("ALDOC","CST3","GFAP","VIM","AQP4","CD63"),])))),cluster_columns = F, show_row_names = T ) 


```

```{r OPC_Oligo}
#psdtime heatmap
AD_OPC_Oligo_pseudotime <- read_csv("AD_OPC_Oligo_pseudotime.csv")
tmp <- starmap@meta.data[starmap@meta.data$top_level %in% c("OPC","Oligo"),]
AD_OPC_Oligo_pseudotime <- data.frame(AD_OPC_Oligo_pseudotime,
                                  normalized_psdtime = AD_OPC_Oligo_pseudotime$pseudotime/max(AD_OPC_Oligo_pseudotime$pseudotime))
AD_OPC_Oligo_pseudotime <- data.frame(AD_OPC_Oligo_pseudotime,
                                  psdtime_stage = floor(10 * AD_OPC_Oligo_pseudotime$normalized_psdtime))
AD_OPC_Oligo_pseudotime$psdtime_stage[AD_OPC_Oligo_pseudotime$psdtime_stage == 10] <- 9

gene_list <- row.names(starmap_obj@assays[["RNA"]]@counts)[
    rowSums(starmap_obj@assays[["RNA"]]@counts[,starmap_obj@meta.data[["top_level"]] %in% c("OPC","Oligo")] > 0)
    > sum(starmap_obj@meta.data[["top_level"]] %in% c("OPC","Oligo")) * 0.01]
tmp_df <- matrix(0, nrow = length(gene_list), ncol = 10) %>% as.data.frame(row.names = gene_list)
colnames(tmp_df) <- paste("stage",0:9,sep = "")
for (i in 0:9) {
    tmp_mat <- starmap_obj@assays[["RNA"]]@counts[gene_list,starmap_obj@meta.data[["top_level"]] %in% c("OPC","Oligo")]
    tmp_df[,i+1] <- rowSums(tmp_mat[,AD_OPC_Oligo_pseudotime$psdtime_stage == i]) /
      sum(AD_OPC_Oligo_pseudotime$psdtime_stage == i)
  }
Heatmap(log2(1+as.matrix(tmp_df[intersect(c("PLP1","MBP","CLDN11","KLK6","SERPINA3N","C4B","CDKN1A","PDGFRA","CACNG4","GPR17"),gene_list),])),
        cluster_columns = F, show_row_names = T ) 

```

            | 8 D| 8 C|13 D|13 C|

2766 dataset\|9723\|9735\|9494\|9498\| 64 dataset\|9721\|9781\|9919\|9930\|

```{r dotplot}
#Combine Seurat
starmap_combined <- subset(starmap_raw, features = row.names(starmap_64@assays$RNA)) %>% 
  merge(y = starmap_64, add.cell.ids = c("G2766_","G64_"), project = "Merged_starmap") %>% 
  subset(subset = top_level == "Astro")

DotPlot(starmap_combined,features = Astro_DC_DE$rowname[Astro_DC_DE$rowname %in% gene_list_64] %>% .[1:10],
        group.by = "sample")

```

## Grid Analysis

```{r grid analysis function}
top_level_palette_list <- top_level_palette_list[c("Ex", "Inhi", "CA1", "CA2", "CA3", "Astro", "Endo", "Micro","Oligo", "OPC", "SMC" )]
ad_tau_grid_analysis <- function(tau_img,cell_meta,sample_name, 
                                 block_size, palette_list, level = "top_level", 
                                 plaque_img = NULL, region_img = NULL){
  plot_list <- list()
  tmp_img <- Image(tau_img!=0,colormode = Grayscale)
  tmp_mat <- matrix(0,nrow = floor(dim(tmp_img)[1] / block_size),
                    ncol = floor(dim(tmp_img)[2] / block_size))
  for(i in 1:dim(tmp_mat)[1]){
    for(j in 1:dim(tmp_mat)[2]){
      tmp_mat[i,j] <- sum(tmp_img[((i-1)*block_size+1):(i*block_size),((j-1)*block_size+1):(j*block_size)])
    }
  }
  require(ComplexHeatmap)
  require(circlize)
  plot_list[["tau_heatmap"]] <- Heatmap(tmp_mat,cluster_rows = F,cluster_columns = F,
                                        col =  colorRamp2(c(0, quantile(tmp_mat,probs = c(0.99))), 
                                                          c("white", "darkred")))
  #Cell Idty Stat
  cell_stat <- data.frame(x = rep(c(1:dim(tmp_mat)[1]), dim(tmp_mat)[2]),
                          y = rep(c(1:dim(tmp_mat)[2]), each = dim(tmp_mat)[1]))
  cell_stat[["tau_level"]] <- apply(cell_stat,1,FUN = function(x){tmp_mat[x[["x"]], x[["y"]] ]})
  for(i in names(palette_list)){
    cell_stat[[i]] <- apply(cell_stat,1,
                            FUN = function(x){
                              sum(cell_meta$x >= (x[["x"]]-1)*block_size+1 &
                                    cell_meta$x <= x[["x"]]*block_size &
                                    cell_meta$y >= (x[["y"]]-1)*block_size+1 &
                                    cell_meta$y <= x[["y"]]*block_size &
                                    cell_meta[[level]] == i)
                              })
    #print(i)
  }
  if(!is.null(region_img)){
    cell_stat[["region"]] <- apply(cell_stat,1,
                            FUN = function(x){
                              region_img[round((x[["x"]]-1/2)*block_size), round((x[["y"]]-1/2)*block_size)]
                              })
  }
  require(reshape2)
  if(!is.null(plaque_img)){
    cell_stat[["plaque"]] <- apply(cell_stat,1,
                                   FUN = function(x){
                                     return(sum(plaque_img[((x[["x"]]-1)*block_size+1):(x[["x"]]*block_size),
                                                        ((x[["y"]]-1)*block_size+1):(x[["y"]]*block_size)]))
                                   })
    tmp_df <- data.frame(tau_interval = c("0%","50%","100%","100%","100%"),
                       min_tau = c(0,quantile(cell_stat$tau_level[cell_stat$tau_level != 0])[c(1,3,3,3)]),
                       max_tau = c(quantile(cell_stat$tau_level[cell_stat$tau_level != 0])[c(1,3)],rep(block_size^2,3)),
                       plaque = c("any","any","any","with_plaque","without_plaque"))
    for(i in 1:5){
      for(j in names(palette_list)){
        if(tmp_df$plaque[i] == "any"){
          tmp_df[[j]][i] <- sum(cell_stat[[j]][cell_stat$tau_level >= tmp_df$min_tau[i] &
                                               cell_stat$tau_level < tmp_df$max_tau[i]])/
          sum(cell_stat$tau_level >= tmp_df$min_tau[i] & cell_stat$tau_level < tmp_df$max_tau[i])
        }else if(tmp_df$plaque[i] == "with_plaque"){
          tmp_df[[j]][i] <- sum(cell_stat[[j]][cell_stat$tau_level >= tmp_df$min_tau[i] &
                                               cell_stat$tau_level < tmp_df$max_tau[i] & cell_stat$plaque > 0])/
          sum(cell_stat$tau_level >= tmp_df$min_tau[i] & cell_stat$tau_level < tmp_df$max_tau[i] & cell_stat$plaque > 0)
        }else if(tmp_df$plaque[i] == "without_plaque"){
          tmp_df[[j]][i] <- sum(cell_stat[[j]][cell_stat$tau_level >= tmp_df$min_tau[i] &
                                               cell_stat$tau_level < tmp_df$max_tau[i] & cell_stat$plaque == 0])/
          sum(cell_stat$tau_level >= tmp_df$min_tau[i] & cell_stat$tau_level < tmp_df$max_tau[i] & cell_stat$plaque == 0)
        }
      }
    }
    tmp_df_bk <- tmp_df 
    tmp_df <- tmp_df %>% melt(id.vars = c("tau_interval","min_tau","max_tau","plaque"))
    tmp_df$tau_interval <- factor(tmp_df$tau_interval, levels = c("0%","50%","100%"))
    tmp_df$variable <- factor(tmp_df$variable, levels = names(palette_list))
    tmp_df[["title"]] <- factor(paste(tmp_df$tau_interval,tmp_df$plaque,sep = "_"),
                                levels = c("0%_any","50%_any","100%_any","100%_with_plaque","100%_without_plaque"))
    
    plot_list[["stacked_barplot"]] <-
    ggplot(data = tmp_df,aes(x = title, y = value, fill = variable, order = variable))+
      geom_bar(stat="identity") + 
      ggtitle(paste(sample_name,"Cell Density in Tau Free blocks and 0-25%/.../75-100% quantile blocks with tau")) +
      scale_fill_manual("",values = palette_list,
                        breaks = names(palette_list),
                        labels = names(palette_list)) +
      theme_classic()
  
  }else{
    #Ridge Barplot
  tmp_df <- data.frame(tau_interval = c("0%","50%","100%"),
                       #min_tau = c(0,1,10,29,68),
                       #max_tau = c(1,10,29,68,999),
                       min_tau = c(0,quantile(cell_stat$tau_level[cell_stat$tau_level != 0])[c(1,3)]),
                       max_tau = c(quantile(cell_stat$tau_level[cell_stat$tau_level != 0])[c(1,3)],block_size^2))
  
  for(i in 1:3){
    for(j in names(palette_list)){
      tmp_df[[j]][i] <- sum(cell_stat[[j]][cell_stat$tau_level >= tmp_df$min_tau[i] &
                                             cell_stat$tau_level < tmp_df$max_tau[i]])/
      sum(cell_stat$tau_level >= tmp_df$min_tau[i] & cell_stat$tau_level < tmp_df$max_tau[i])
    }
    
  }
  tmp_df_bk <- tmp_df 
  tmp_df <- tmp_df %>% melt(id.vars = c("tau_interval","min_tau","max_tau"))
  tmp_df$tau_interval <- factor(tmp_df$tau_interval, levels = c("0%","50%","100%"))
  tmp_df$variable <- factor(tmp_df$variable, levels = names(palette_list))
  
  plot_list[["stacked_barplot"]] <-
    ggplot(data = tmp_df,aes(x = tau_interval, y = value, fill = variable, order = variable))+
    geom_bar(stat="identity") + 
    ggtitle(paste(sample_name,"Cell Density in Tau Free blocks and 0-25%/.../75-100% quantile blocks with tau")) +
    scale_fill_manual("",values = palette_list,
                      breaks = names(palette_list),
                      labels = names(palette_list)) +
    theme_classic()
  }
  
  
    
  return(list("plot_list" = plot_list,
              "cell_stat" = cell_stat,
              "interval_stat" = tmp_df_bk))
}
```

```{r}
#####Run tau grid analysis#####
cell_meta <- starmap_raw@meta.data %>% subset(subset = sample == "AD_mouse9494")
sample_name <- "AD_mouse9494"
block_size = round(20*3.175) #20um
tau_img <- starmap_raw@misc[["AD_mouse9494_morph"]][["tau"]]
plaque_img <- starmap@misc$AD_mouse9494_plaque_all$AD_mouse9494_plaque_img
region_img <- starmap@misc$AD_mouse9494_morph$region
#1-Alveus
require(tiff)
region_img <- readTIFF(source = "data/2021-06-22-mAD-molecular-labels/2766\ genes/AD_mouse9494-molecular-labels.tif",
                       indexed = T) %>% t()

AD9494_res <- ad_tau_grid_analysis(starmap_raw@misc[["AD_mouse9494_morph"]][["tau"]],
                                   subset(starmap_raw@meta.data, subset = sample == "AD_mouse9494"), "AD_mouse9494", block_size, top_level_palette_list, plaque_img = starmap@misc$AD_mouse9494_plaque_all$AD_mouse9494_plaque_img)
AD9723_res <- ad_tau_grid_analysis(starmap_raw@misc[["AD_mouse9723_morph"]][["tau"]],
                                   subset(starmap_raw@meta.data, subset = sample == "AD_mouse9723"), "AD_mouse9723", block_size, top_level_palette_list, plaque_img = starmap@misc$AD_mouse9723_plaque_all$AD_mouse9723_plaque_img)

AD9919_res <- ad_tau_grid_analysis(starmap_64@misc[["AD_mouse9919_morph"]][["tau"]],
                                   subset(starmap_64@meta.data, subset = sample == "AD_mouse9919"), "AD_mouse9919", block_size, top_level_palette_list)
AD9721_res <- ad_tau_grid_analysis(starmap_64@misc[["AD_mouse9721_morph"]][["tau"]],
                                   subset(starmap_64@meta.data, subset = sample == "AD_mouse9721"), "AD_mouse9721", block_size, top_level_palette_list)

#Oligo/OPC subtype
starmap@meta.data$cell_type[starmap@meta.data$cell_type == "OPC_Gpr17"] <- "OPC"
starmap_64@meta.data$cell_type[starmap_64@meta.data$cell_type == "OPC_Gpr17"] <- "OPC"

tmp_palette <- c("#2fe04d","#2c73e6","#fa733e","#8600d4")
names(tmp_palette) <- c("Oligo", "Oligo_Klk6", "Oligo_Cldn11","OPC")

AD9494_Oligo_res <- ad_tau_grid_analysis(starmap_raw@misc[["AD_mouse9494_morph"]][["tau"]],
                                   subset(starmap_raw@meta.data, subset = sample == "AD_mouse9494"), 
                                   "AD_mouse9494", block_size, tmp_palette, level = "cell_type",
                                   starmap@misc$AD_mouse9494_plaque_all$AD_mouse9494_plaque_img)
AD9723_Oligo_res <- ad_tau_grid_analysis(starmap_raw@misc[["AD_mouse9723_morph"]][["tau"]],
                                   subset(starmap_raw@meta.data, subset = sample == "AD_mouse9723"), 
                                   "AD_mouse9723", block_size, tmp_palette, level = "cell_type",
                                   starmap@misc$AD_mouse9723_plaque_all$AD_mouse9723_plaque_img)
AD9919_Oligo_res <- ad_tau_grid_analysis(starmap_64@misc[["AD_mouse9919_morph"]][["tau"]],
                                   subset(starmap_64@meta.data, subset = sample == "AD_mouse9919"), "AD_mouse9919", block_size, tmp_palette, level = "cell_type")
AD9721_Oligo_res <- ad_tau_grid_analysis(starmap_64@misc[["AD_mouse9721_morph"]][["tau"]],
                                   subset(starmap_64@meta.data, subset = sample == "AD_mouse9721"), "AD_mouse9721", block_size, tmp_palette, level = "cell_type")
plot_list <- list(AD9494_Oligo_res[["plot_list"]][["stacked_barplot"]],AD9723_Oligo_res[["plot_list"]][["stacked_barplot"]],
                  AD9919_Oligo_res[["plot_list"]][["stacked_barplot"]],AD9721_Oligo_res[["plot_list"]][["stacked_barplot"]])


pdf(file = "Tau_stacked_barplot.pdf",width = 12,height = 9,useDingbats = FALSE)
AD9723_Oligo_res[["plot_list"]][["stacked_barplot"]] %>% print()
AD9494_Oligo_res[["plot_list"]][["stacked_barplot"]] %>% print()
#AD9721_res[["plot_list"]][["stacked_barplot"]] %>% print()
#AD9919_res[["plot_list"]][["stacked_barplot"]] %>% print()
dev.off()
#####Stat Test#####
#wilcox test
cell_stat <- AD9723_Oligo_res$cell_stat
tmp_df <- AD9723_Oligo_res$interval_stat
for(i in colnames(tmp_df)[5:dim(tmp_df)[2]]){
  for(j in 1:dim(tmp_df)[1]){
    if(tmp_df$plaque[j] == "any"){
      tmp_vec1 <- cell_stat[[i]][cell_stat$tau_level >= tmp_df$min_tau[j] & 
                                 cell_stat$tau_level < tmp_df$max_tau[j]]
    }else if(tmp_df$plaque[j] == "with_plaque"){
      tmp_vec1 <- cell_stat[[i]][cell_stat$tau_level >= tmp_df$min_tau[j] & 
                                 cell_stat$tau_level < tmp_df$max_tau[j] & cell_stat$plaque > 0]
    }else{
      tmp_vec1 <- cell_stat[[i]][cell_stat$tau_level >= tmp_df$min_tau[j] & 
                                 cell_stat$tau_level < tmp_df$max_tau[j] & cell_stat$plaque == 0]
    }
    
    tmp_vec2 <- cell_stat[[i]][cell_stat$tau_level == 0]
    tmp_df[j,i] <- wilcox.test(tmp_vec1,tmp_vec2)$p.value
  }
}
tmp_df <- t(tmp_df[2:5,5:8])

#####Oligo Tau DE#####
AD9494_Oligo_res <- ad_tau_grid_analysis(starmap_raw@misc[["AD_mouse9494_morph"]][["tau"]],
                                   subset(starmap_raw@meta.data, subset = sample == "AD_mouse9494"), 
                                   "AD_mouse9494", block_size, tmp_palette, level = "cell_type",
                                   starmap@misc$AD_mouse9494_plaque_all$AD_mouse9494_plaque_img,
                                   region_img = region_img)
#(High Tau vs other)
cell_stat <- AD9494_Oligo_res$cell_stat
#Get Quantile
quantile(cell_stat$tau_level)
seurat_obj <- subset(starmap_raw,subset = sample == "AD_mouse9494" & top_level == "Oligo")
seurat_obj@misc <- list()
#subset and label Oligo
seurat_obj@meta.data <- data.frame(seurat_obj@meta.data, block_tau = 0, block_plaque = 0, 
                                   block_tau_flag = F, block_tnp_flag = F,
                                   alveus_flag = F)
seurat_obj@meta.data$block_tau <- apply(seurat_obj@meta.data,1,
                                             FUN = function(x){
                                               pos_x <- as.numeric(x[["x"]])
                                               pos_y <- as.numeric(x[["y"]])
                                               if(pos_x > max(cell_stat$x)*block_size | 
                                                  pos_y > max(cell_stat$y)*block_size){
                                                 return(-1)
                                               }else{
                                                 return(cell_stat$tau_level[cell_stat$x == 1+floor((pos_x-1)/block_size) &
                                                                     cell_stat$y == 1+floor((pos_y-1)/block_size)])
                                               }
                                             }) %>% unlist(use.names = F)
seurat_obj@meta.data$block_plaque <- apply(seurat_obj@meta.data,1,
                                             FUN = function(x){
                                               pos_x <- as.numeric(x[["x"]])
                                               pos_y <- as.numeric(x[["y"]])
                                               if(pos_x > max(cell_stat$x)*block_size | 
                                                  pos_y > max(cell_stat$y)*block_size){
                                                 return(-1)
                                               }else{
                                                 return(cell_stat$plaque[cell_stat$x == 1+floor((pos_x-1)/block_size) &
                                                                     cell_stat$y == 1+floor((pos_y-1)/block_size)])
                                               }
                                             }) %>% unlist(use.names = F)
seurat_obj@meta.data$block_tnp_flag <- apply(seurat_obj@meta.data,1,
                                             FUN = function(x){
                                               return(ifelse(as.numeric(x[["block_tau"]]) > 
                                                               quantile(cell_stat$tau_level[cell_stat$tau_level != 0])[3],
                                                             ifelse(as.numeric(x[["block_plaque"]]) > 0,"High-tau/plaque","High-tau/normal"),
                                                             ifelse(as.numeric(x[["block_tau"]]) > 0,"Low-tau","No-tau")))
                                             })
seurat_obj@meta.data$block_tau_flag <- apply(seurat_obj@meta.data,1,
                                             FUN = function(x){
                                               return(ifelse(as.numeric(x[["block_tau"]]) > 
                                                               quantile(cell_stat$tau_level[cell_stat$tau_level != 0])[3],
                                                             "High-tau",
                                                             ifelse(as.numeric(x[["block_tau"]]) > 0,"Low-tau","No-tau")))
                                               #return(ifelse(as.numeric(x[["block_tau"]]) > 0,
                                               #              "Tau_pos", "Tau_neg"))
                                             })
seurat_obj@meta.data$alveus_flag <- apply(seurat_obj@meta.data,1,
                                             FUN = function(x){
                                                pos_x <- as.numeric(x[["x"]])
                                                pos_y <- as.numeric(x[["y"]])
                                                if(pos_x <= max(cell_stat$x)*block_size & 
                                                   pos_y <= max(cell_stat$y)*block_size){
                                                  if(cell_stat$region[cell_stat$x == 1+floor((pos_x-1)/block_size) &
                                                                     cell_stat$y == 1+floor((pos_y-1)/block_size)] == 2)
                                                   return(T)
                                                  else return(F) 
                                               }else return(F)
                                             })

seurat_obj <- subset(seurat_obj,subset = block_tau != -1 & alveus_flag == T)

seurat_obj <- SetIdent(seurat_obj,value = "block_tau_flag")
seurat_obj <- NormalizeData(seurat_obj, normalization.method = "LogNormalize", scale.factor = 10000)
seurat_obj <- ScaleData(seurat_obj, features = rownames(seurat_obj))
seurat_obj.average <- AverageExpression(seurat_obj,return.seurat = T)

Oligo_tau_DE <- FindMarkers(seurat_obj,ident.1 = "High-tau")

DoHeatmap(seurat_obj.average,
          features = row.names(Oligo_tau_DE)[Oligo_tau_DE$p_val_adj<0.05])
#AverageExpression Heatmap
seurat_obj.average <- AverageExpression(seurat_obj,return.seurat = T)
Oligo_tau_DE <- left_join(data.frame(Gene = row.names(Oligo_tau_DE),Oligo_tau_DE),
                          data.frame(Gene = row.names(seurat_obj.average@assays[["RNA"]]@data),seurat_obj.average@assays[["RNA"]]@data),
                          by = "Gene")
write_csv(Oligo_tau_DE, path = "Oligo_tau_DE.csv")
Heatmap()
#####Oligo Plaque DE#####
seurat_obj <- subset(starmap_raw,subset = sample == "AD_mouse9494" & top_level == "Oligo")
seurat_obj@misc <- list()
require(dplyr)
seurat_obj@meta.data <- starmap@misc$AD_mouse9494_plaque_all$AD_mouse9494_cell_meta %>% 
  subset(subset = top_level == "Oligo") %>% .[,c("orig_index","min_border_dist","nearest_plaque")] %>% left_join(y = seurat_obj@meta.data, by = c("orig_index"))
seurat_obj@meta.data$plaque_flag <- apply(seurat_obj@meta.data,1,
                                             FUN = function(x){
                                               return(ifelse(as.numeric(x[["min_border_dist"]]) < 25*3.3,"Near","Far"))
                                             })

seurat_obj <- SetIdent(seurat_obj,value = "plaque_flag")
seurat_obj <- NormalizeData(seurat_obj, normalization.method = "LogNormalize", scale.factor = 10000)
seurat_obj <- ScaleData(seurat_obj, features = rownames(seurat_obj))
Oligo_plaque_DE <- FindMarkers(seurat_obj,ident.1 = "Near")
write_csv(data.frame(Gene = row.names(Oligo_plaque_DE),Oligo_plaque_DE),path = "Oligo_plaque_DE.csv")




ad_area_stat <- function(starmap_obj, tmp_img, sample_name, area_, Oligo = F){
  if(area_ == "alveus") area_ <- "1"
  else if(area_ == "SLM") area_ <- "2"
  library(tiff)
  cell_meta <- starmap_obj@meta.data[starmap_obj@meta.data$sample == sample_name,] %>% data.frame(area_label = 0)
  cell_meta$area_label <- apply(cell_meta,1,FUN = function(x){tmp_img[as.numeric(x[["x"]]), as.numeric(x[["y"]])]}) - 1
  if(Oligo){
    tmp <- cell_meta %>% subset(subset = area_label == area_ & top_level %in% c("OPC","Oligo")) %>% 
    group_by(cell_type) %>% 
    summarise(n = n()) %>% 
    arrange(cell_type) %>% 
    right_join(data.frame(cell_type = cell_type_list$Oligo), by = c("cell_type"))  %>% as.data.frame()
    row.names(tmp) <- tmp$cell_type
  }else{
    tmp <- cell_meta %>% subset(subset = area_label == area_) %>% 
    group_by(top_level) %>% 
    summarise(n = n()) %>% 
    arrange(top_level) %>% 
    right_join(data.frame(top_level = names(top_level_palette_list)), by = c("top_level"))  %>% as.data.frame()
    row.names(tmp) <- tmp$top_level
  }
  
  tmp$n[is.na(tmp$n)] = 0
  tmp$n <- 3.175^2 * 1000000 * tmp$n/sum(tmp_img == (1+as.numeric(area_)))
  if(Oligo) return(tmp[c("Oligo","Oligo_Klk6","Oligo_Cldn11","OPC"),2]) 
    else return(tmp[c("Astro","Micro","Oligo","OPC"),2]) 
  
}

require(tiff)
require(tidyverse)
require(reshape2)
area_stat_df <- data.frame(top_level = c("Astro","Micro","Oligo","OPC"))
area_stat_df <- data.frame(cell_type = c("Oligo","Oligo_Klk6","Oligo_Cldn11","OPC"))
for(i in c("AD_mouse9735","AD_mouse9723","AD_mouse9498","AD_mouse9494")){
  file_name = paste("/Users/zhouhaowen/Desktop/At_Broad/AD/data/2021-06-22-mAD-molecular-labels/2766\ genes/",i,"-molecular-labels.tif",sep = "")
    tmp_img <- readTIFF(source = file_name,indexed = T) %>% t()
  for(j in c("alveus","SLM")){
    area_stat_df[[paste(i,j,sep = "_")]] <- ad_area_stat(starmap, tmp_img,i,j,Oligo = F)
  }
}
for(i in c("AD_mouse9781","AD_mouse9721","AD_mouse9930","AD_mouse9919")){
  file_name = paste("/Users/zhouhaowen/Desktop/At_Broad/AD/data/2021-06-22-mAD-molecular-labels/64\ genes/",i,"-molecular-labels.tif",sep = "")
    tmp_img <- readTIFF(source = file_name,indexed = T) %>% t()
  for(j in c("alveus","SLM")){
    area_stat_df[[paste(i,j,sep = "_")]] <- ad_area_stat(starmap_64, tmp_img,i,j)
  }
}
tmp_df <- area_stat_df[,c(1,seq(from = 2, to = 16, length.out = 8))] %>% melt(id.vars = c("top_level"))
tmp_df <- area_stat_df[,c(1,seq(from = 3, to = 17, length.out = 8))] %>% melt(id.vars = c("top_level"))
ggplot(data = tmp_df,aes(x = variable, y = value, fill = top_level))+
    geom_bar(stat="identity") + 
    #ggtitle(paste(sample_name,"Cell Density in Tau Free blocks and 0-25%/.../75-100% quantile blocks with tau")) +
    scale_fill_manual("",values = top_level_palette_list,
                      breaks = names(top_level_palette_list),
                      labels = names(top_level_palette_list)) +
    theme_classic() +
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

tmp_df <- area_stat_df[,c(1,seq(from = 2, to = 16, length.out = 8))] %>% melt(id.vars = c("cell_type"))
ggplot(data = tmp_df,aes(x = variable, y = value, fill = cell_type))+
    geom_bar(stat="identity") + 
    #ggtitle(paste(sample_name,"Cell Density in Tau Free blocks and 0-25%/.../75-100% quantile blocks with tau")) +
    scale_fill_manual("",values = cell_type_palette_list$Oligo,
                      breaks = cell_type_list$Oligo,
                      labels = cell_type_list$Oligo) +
    theme_classic() +
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

cell_meta <- starmap@misc$AD_mouse9494_plaque_all$AD_mouse9494_cell_meta %>% 
  subset(x < dim(tmp_mat)[1]*100 & y < dim(tmp_mat)[2]*100) %>%
  data.frame(tau_group = tmp_mat[cbind(1+floor(.$x/100), 1+floor(.$y/100))]) %>%
  mutate(tau_group = apply(.,MARGIN = 1,
                           FUN = function(x){
                             if(as.numeric(x[["tau_group"]]) < 1) return("none")
                             else if(as.numeric(x[["tau_group"]]) < 100) return("medium")
                             else return("dense")
                           }) )
tmp_starmap <- subset(starmap_scaled,subset = sample == "AD_mouse9494" & orig_index %in% cell_meta$orig_index)
tmp_starmap@meta.data <- tmp_starmap@meta.data %>% data.frame(tau_group = cell_meta$tau_group)
tmp_starmap <- subset(starmap_scaled,subset = top_level == "DG")
tmp_starmap <- SetIdent(object = tmp_starmap, value  = tmp_starmap@meta.data[["tau_group"]])
de_res <- FindMarkers(tmp_starmap,ident.1 = "dense",ident.2 = "none",logfc.threshold = 0)


```

##Tau Spatial

```{r tau/gfap}
#Tau Stat
sample_name <- "AD_mouse9494"
sample_name <- "AD_mouse9723"
cell_meta <- starmap@meta.data %>% subset(subset = sample == sample_name & top_level %in% 
                                            c("Ex","CA1","CA2","CA3","DG"))
cell_meta <- starmap@meta.data %>% subset(subset = sample == sample_name & top_level %in% 
                                            c("Inhi"))
tmp_df <- data.frame(sample = rep(c("AD_mouse9723","AD_mouse9494"),each = 14),
                     class = rep(c(rep(c("Ex"),8),rep("Inhi",6)),2),
                     cell_type = rep(c(cell_type_list$Ex,cell_type_list$CADG,cell_type_list$Inhi),2),
                     p_val = 0)
for(i in cell_type_list$Inhi){
#for(i in c(cell_type_list$Ex,cell_type_list$CADG)){
  tmp_vec <- rep(0,4)
  tmp_vec[1] <- sum(cell_meta$cell_type == i & cell_meta$tau > 7)
  tmp_vec[2] <- sum(cell_meta$cell_type == i) - tmp_vec[1]
  tmp_vec[3] <- sum(cell_meta$tau > 7) - tmp_vec[1]
  tmp_vec[4] <- sum(cell_meta$cell_type != i & cell_meta$tau <= 7)
  a <- chisq.test(matrix(tmp_vec,ncol = 2),simulate.p.value = T)$p.value
  tmp_df$p_val[tmp_df$sample == sample_name & tmp_df$cell_type == i] <- a
  #print(tmp_vec)
  #print(paste(sample_name,i,"chi-square test:",a))
}






#Using Scaled Obj
#Add Tau flag to meta data
starmap_scaled <- ad_starmap_normalize(starmap_raw)
#starmap_scaled <- ad_starmap_normalize(starmap_64)
starmap_scaled@meta.data <- starmap_scaled@meta.data %>% data.frame(tau_flag = ifelse(.$tau > 7,"Tau","Normal"))
starmap_scaled <- SetIdent(object = starmap_scaled, value  = starmap_scaled@meta.data[["tau_flag"]])
tmp_starmap <- subset(starmap_scaled,subset = top_level == "CA1" & ((sample == "AD_mouse9494" & tau_flag == "Tau") |
                        sample == "AD_mouse9498"))

de_res <- FindMarkers(tmp_starmap,ident.1 = "Tau",ident.2 = "Normal",logfc.threshold = 0) %>% subset(subset = p_val < 0.05)

de_res_64 <- FindMarkers(tmp_starmap,ident.1 = "Tau",ident.2 = "Normal",logfc.threshold = 0)

gene_list_tau <- intersect(row.names(de_res_64)[de_res_64$p_val < 0.05],row.names(de_res)[de_res$p_val < 0.05])

DotPlot(object = starmap_scaled, features = gene_list_tau) + coord_flip()
DotPlot(object = starmap_scaled, features = row.names(de_res)[1:10]) + coord_flip()

#Tau Distribution Around hippocampus area
tau_img <- Image(starmap@misc[["AD_mouse9494_morph"]][["tau"]],colormode = Grayscale)

plaque_img <- starmap@misc$`AD_mouse9494_plaque_Cortex`$AD_mouse9494_plaque_img
AD9494_tau_vec <- rep(0,5)
AD9494_plaque_vec <- starmap@misc[["AD_mouse9494_plaque_Cortex"]][["AD_mouse9494_plaque_dilate_area"]]
for(i in 1:5){
  tmp_img <- dilate(plaque_img, kern = makeBrush(round(3.175*20*i), shape = "disc"))
  AD9494_tau_vec[i] <- sum(tau_img & tmp_img)
}
tmp_vec <- rep(0,5)
for(i in 2:5){
  tmp_vec[i] <- AD9494_tau_vec[i]-AD9494_tau_vec[i-1] 
}
tmp_vec[1] <- AD9494_tau_vec[1]

plot_list[[1]] <- ggplot(data=data.frame(group = paste(c(1:5),"0um",sep = ""), tau = tmp_vec/AD9494_plaque_vec), aes(x=group, y=tau)) +
  theme_classic() +
  geom_bar(stat="identity",fill = "darkred") +
  labs(title = "Tau Hippocampus")
pdf(file = "F6_tau_distr.pdf",width = 6,height = 4.5,useDingbats = FALSE)
plot_list %>% print()
dev.off()

AD9919_fig <- list()
AD9919_fig[["GFAP"]] <- readImage("data/2021-04-28-protein-images/gfap/AD_mouse9930.tif")
AD9919_fig[["GFAP"]] <- AD9919_fig[["GFAP"]][1:5885,1:6708]
AD9919_fig[["Plaque"]] <- starmap_64@misc[["AD_mouse9919_morph"]][["plaque"]]
AD9919_tau_vec <- rep(0,5)
AD9919_plaque_vec <- rep(0,5)
for(i in 1:5){
  tmp_img <- dilate(AD9919_fig[["Plaque"]], kern = makeBrush(33 * i, shape = "disc"))
  AD9919_tau_vec[i] <- sum(AD9919_fig[["GFAP"]] & tmp_img)
  AD9919_plaque_vec[i]  <- sum(tmp_img)
}
ggplot(data=data.frame(group = paste(c(1:5),"0um",sep = ""), gfap = AD9919_tau_vec/AD9919_plaque_vec), aes(x=group, y=gfap)) +
  theme_classic() +
  geom_bar(stat="identity",fill = "darkred")
```

```{r Neuron-Tau}
cell_meta <- subset(starmap@meta.data,
                    subset = sample == "AD_mouse9494" & top_level %in% c("Ex", "CA1", "CA2", "CA3", "DG") &
                      tau > 0)

ggplot(cell_meta, aes(x=cell_type, y=tau, fill=cell_type)) + 
  geom_violin(trim=FALSE)+
  geom_boxplot(width=0.1, fill="white")+
  labs(title="Tau violin plot",x="Dose (mg)", y = "Length") +
  theme_classic()
```

```{r CA1-3/DG around Plaque Sub-cortical}
palette_list <- cell_type_palette_list[["CADG"]]
names(palette_list) <- cell_type_list[["CADG"]]
pdf(file = "F6_CADG_comp.pdf",width = 6,height = 4.5,useDingbats = FALSE)
ad_hl_cell_distr(starmap@misc[["AD_mouse9494_plaque_Sub-cortical"]][["AD_mouse9494_cell_meta"]]$min_border_dist,
                           starmap@misc[["AD_mouse9494_plaque_Sub-cortical"]][["AD_mouse9494_cell_meta"]]$cell_type,
                           palette_list = palette_list,
                           scale = "percentage",title = paste("CADG","Sub-cortical 9494"),y_min = 0,y_max = 0.55) %>% print()

ad_hl_cell_distr(starmap@misc[["AD_mouse9723_plaque_Sub-cortical"]][["AD_mouse9723_cell_meta"]]$min_border_dist,
                           starmap@misc[["AD_mouse9723_plaque_Sub-cortical"]][["AD_mouse9723_cell_meta"]]$cell_type,
                           palette_list = palette_list,
                           scale = "percentage",title = paste("CADG","Sub-cortical 9723"),y_min = 0,y_max = 0.55) %>% print()
dev.off()

```

##Type-to-type dist and ridge plot

```{r type-to-type dist and ridge plot}

#Ex,Inhi,CA1-3 -> Neuron, Oligo,DAA,DAM
cell_meta <- starmap@meta.data
cell_meta$cell_type <- ifelse(starmap@meta.data$cell_type %in% c(cell_type_list[["Ex"]], 
                                                                 cell_type_list[["Inhi"]], 
                                                                 cell_type_list[["CADG"]]),
                                      "Neuron",
                                      ifelse(starmap@meta.data$cell_type %in% cell_type_list[["Oligo"]][1:3],
                                             "Oligo",
                                             ifelse(starmap@meta.data$cell_type == "Astro_Gfap/Vim",
                                                    "DAA",
                                                    ifelse(starmap@meta.data$cell_type == "Micro_Cst7/Ctsb",
                                                           "DAM",
                                                           ifelse(starmap@meta.data$cell_type %in% cell_type_list[["OPC"]],
                                                                        "OPC","Other")))))
Sub_cluster_dist <- list()
Sub_cluster_dist[["AD9494"]] <- ad_calc_cluster_dist(cell_meta = cell_meta,
                                                  sample_name = "AD_mouse9494",
                                                  region = "all",
                                                  Sub_level_clusters = c("DAM","DAA","Neuron"),
                                                  plaque_meta = starmap@misc$AD_mouse9494_plaque_all$AD_mouse9494_plaque_meta)
Sub_cluster_dist[["AD9494_Shuffle"]] <- ad_calc_cluster_dist(cell_meta = cell_meta,
                                                  sample_name = "AD_mouse9494",
                                                  region = "all",
                                                  Sub_level_clusters = c("DAM","DAA","Neuron"),shuffle = T,
                                                  plaque_meta = starmap@misc$AD_mouse9494_plaque_all$AD_mouse9494_plaque_meta)

Sub_cluster_dist[["AD9723"]] <- ad_calc_cluster_dist(cell_meta = cell_meta,
                                                  sample_name = "AD_mouse9723",
                                                  region = "all",
                                                  Sub_level_clusters = c("DAM","DAA","Neuron"),
                                                  plaque_meta = starmap@misc$AD_mouse9723_plaque_all$AD_mouse9723_plaque_meta)
Sub_cluster_dist[["AD9723_Shuffle"]] <- ad_calc_cluster_dist(cell_meta = cell_meta,
                                                  sample_name = "AD_mouse9723",
                                                  region = "all",
                                                  Sub_level_clusters = c("DAM","DAA","Neuron"),shuffle = T,
                                                  plaque_meta = starmap@misc$AD_mouse9723_plaque_all$AD_mouse9723_plaque_meta)


Sub_cluster_dist[["AD9494"]]$type_from <- 
  factor(Sub_cluster_dist[["AD9494"]]$type_from,levels = c("plaque","DAM","DAA","Neuron"))
Sub_cluster_dist[["AD9494"]]$type_to <- 
  factor(Sub_cluster_dist[["AD9494"]]$type_to,levels = rev(c("plaque","DAM","DAA","Neuron")))

Sub_cluster_dist[["AD9494_Shuffle"]]$type_from <- 
  factor(Sub_cluster_dist[["AD9494_Shuffle"]]$type_from,levels = c("plaque","DAM","DAA","Neuron"))
Sub_cluster_dist[["AD9494_Shuffle"]]$type_to <- 
  factor(Sub_cluster_dist[["AD9494_Shuffle"]]$type_to,levels = rev(c("plaque","DAM","DAA","Neuron")))

Sub_cluster_dist[["AD9723"]]$type_from <- 
  factor(Sub_cluster_dist[["AD9723"]]$type_from,levels = c("plaque","DAM","DAA","Neuron"))
Sub_cluster_dist[["AD9723"]]$type_to <- 
  factor(Sub_cluster_dist[["AD9723"]]$type_to,levels = rev(c("plaque","DAM","DAA","Neuron")))

Sub_cluster_dist[["AD9723_Shuffle"]]$type_from <- 
  factor(Sub_cluster_dist[["AD9723_Shuffle"]]$type_from,levels = c("plaque","DAM","DAA","Neuron"))
Sub_cluster_dist[["AD9723_Shuffle"]]$type_to <- 
  factor(Sub_cluster_dist[["AD9723_Shuffle"]]$type_to,levels = rev(c("plaque","DAM","DAA","Neuron")))

plot_list <- list()
plot_list[[1]] <- ad_plot_type_dist(Sub_cluster_dist$AD9494,Sub_cluster_dist$AD9494_Shuffle,"AD9494","Shuffled")
plot_list[[2]] <- ad_plot_type_dist(Sub_cluster_dist$AD9723,Sub_cluster_dist$AD9723_Shuffle,"AD9723","Shuffled")

#Density Ridges
cell_meta <- starmap@misc$AD_mouse9494_plaque_all$AD_mouse9494_cell_meta
cell_meta$cell_type <- ifelse(cell_meta$cell_type %in% c(cell_type_list[["Ex"]], 
                                                                 cell_type_list[["Inhi"]], 
                                                                 cell_type_list[["CADG"]]),
                                      "Neuron",
                                      ifelse(cell_meta$cell_type  %in% cell_type_list[["Oligo"]][1:3],
                                             "Oligo",
                                             ifelse(cell_meta$cell_type  == "Astro_Gfap/Vim",
                                                    "DAA",
                                                    ifelse(cell_meta$cell_type  == "Micro_Cst7/Ctsb",
                                                           "DAM",
                                                           ifelse(cell_meta$cell_type  %in% cell_type_list[["OPC"]],
                                                                  "OPC","Other")))))
library(ggridges)

cell_meta <- filter(cell_meta, cell_type!= "Other" & interval %in% paste(1:4,"0um",sep=""))
#cell_meta <- filter(cell_meta, cell_type!= "Other" & min_dist < 330 & region == "Hippocampus")
cell_meta$min_border_dist <- cell_meta$min_border_dist/3.175
cell_meta$cell_type <- 
  factor(cell_meta$cell_type,levels = rev(c("DAM","DAA","OPC","Oligo","Neuron")))
plot_list[[3]] <- 
  ggplot(data = cell_meta,
       aes(x = min_border_dist, y = cell_type, fill = cell_type, height = ..density..)) +
  labs(x = "Min_dist(micron)")+
  #geom_density_ridges(stat = "density", adjust = 0.4) +
  geom_density_ridges(stat = "binline", scale = 1, draw_baseline = F,binwidth = 10,center = 5) +
  scale_x_continuous(expand = c(0, 0)) +
  coord_cartesian(xlim = c(0,40)) +
  scale_y_discrete(expand = expansion(mult = c(0.01, 0.3))) +
  scale_fill_manual(values = rev(c("#fcb900","#29e322","#8600d4","#c800cc","#aaaaaa")))
  theme_ridges()
  
pdf(file = "F7_13mo_type_dist_n_ridge.pdf",width = 6,height = 4.5,useDingbats = FALSE)
plot_list %>% print()
dev.off()
  
sample_name <- "AD9723"
tmp <- cell_stat_res[[paste(sample_name,"A",sep="_")]]
tmp_df <- data.frame(cell_type = c("DAM","DAA","Oligo2/3","OPC","Neuron"),
                       R10 = c(tmp$Micro$res_dens_df$`10um`[3],  tmp$Astro$res_dens_df$`10um`[3],
                               tmp$Oligo$res_dens_df$`10um`[2] + tmp$Oligo$res_dens_df$`10um`[3],
                               tmp$Oligo$res_dens_df$`10um`[4], sum(tmp$Top_level$res_dens_df$`10um`[c(1:2,4:7)])),
                       R20 = c(tmp$Micro$res_dens_df$`20um`[3],  tmp$Astro$res_dens_df$`20um`[3],
                               tmp$Oligo$res_dens_df$`20um`[2] + tmp$Oligo$res_dens_df$`20um`[3],
                               tmp$Oligo$res_dens_df$`20um`[4], sum(tmp$Top_level$res_dens_df$`20um`[c(1:2,4:7)])),
                       R30 = c(tmp$Micro$res_dens_df$`30um`[3],  tmp$Astro$res_dens_df$`30um`[3],
                               tmp$Oligo$res_dens_df$`30um`[2] + tmp$Oligo$res_dens_df$`30um`[3],
                               tmp$Oligo$res_dens_df$`30um`[4], sum(tmp$Top_level$res_dens_df$`30um`[c(1:2,4:7)])),
                       R40 = c(tmp$Micro$res_dens_df$`40um`[3],  tmp$Astro$res_dens_df$`40um`[3],
                               tmp$Oligo$res_dens_df$`40um`[2] + tmp$Oligo$res_dens_df$`40um`[3],
                               tmp$Oligo$res_dens_df$`40um`[4], sum(tmp$Top_level$res_dens_df$`40um`[c(1:2,4:7)])))


library(reshape2)
tmp_df <- tmp_df %>% melt(id = c("cell_type"))
tmp_df$cell_type <- 
  factor(tmp_df$cell_type,levels = c("DAM","DAA","Oligo2/3","OPC","Neuron"))
plot_list <- list()

for(i in 1:5){
  plot_list[[i]] <- ggplot(tmp_df[tmp_df$cell_type == c("DAM","DAA","Oligo2/3","OPC","Neuron")[i],], 
                           aes(x = variable, y=value)) + # the fill argument sets the color for the bars
 geom_col(show.legend = F,fill = c("#fcb900","#29e322","#8600d4","#c800cc","#aaaaaa")[i]) +
    labs(title = c("DAM","DAA","Oligo2/3","OPC","Neuron")[i])+
    ylim(0,c(1300,180,110,90,1500)[i])+
 #scale_fill_manual(values = c("#fcb900","#29e322","#8600d4","#c800cc","#aaaaaa")) +
 theme_classic() 
}


  
```

```{r}
ggplot(subset(plaque_meta,s.area > 1),aes(x= s.area/(3.3^2),fill = sample)) +
  theme_classic() +
  geom_histogram(alpha=0.5, 
                position="identity") +
  geom_vline(xintercept = 400/3.3^2)

ggplot(subset(plaque_meta,s.area > 1),aes(x= s.area/(3.3^2),fill = sample)) +
  theme_classic() +
  geom_density(alpha=0.5) +
  geom_vline(xintercept = 400/3.3^2)
```
## Chi-square test
```{r chi-square test}
res_df <- ad_cell_stat(starmap,"AD_mouse9494","top_level",raw_count = T)
test_df <- data.frame(cell_type = res_df$top_level,
                      region = res_df$region,
                      cell_partition_10 = 0,
                      other_partition_10 = 0,
                      cell_partition_all = 0,
                      other_partition_all = 0,
                      p_val = 1,
                      sig = F)
for(i in 1:dim(test_df)[1]){
  tmp <- res_df[res_df$top_level == test_df$cell_type[i] & res_df$region == test_df$region[i],]
  test_df$cell_partition_10[i] <- tmp$Percentage_10um
  test_df$cell_partition_all[i] <- tmp$Percentage_all
  test_df$other_partition_10[i] <- sum(res_df$Percentage_10um[res_df$top_level != test_df$cell_type[i] & res_df$region == test_df$region[i]])
  test_df$other_partition_all[i] <- sum(res_df$Percentage_all[res_df$top_level != test_df$cell_type[i] & res_df$region == test_df$region[i]])
  test_df$p_val[i] <- chisq.test(matrix(as.numeric(test_df[i,3:6]),ncol = 2))$p.value
  if(!is.na(test_df$p_val[i]) & test_df$p_val[i] < 0.05) test_df$sig[i] <- T
}






```
